imports:
    - { resource: config_dev.yml }

doctrine:
    dbal:
        dbname:   "spg2"
        user:     "spg2"
        password: "ich2000"

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        name: MOCKSESSID
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_functional_test: ~