imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            excluded_404s:
                - ^/
            handler: grouped
        grouped:
            type: group
            members: [streamed,buffered]
        streamed:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        buffered:
            type:   buffer
            handler: swift
        swift:
            type: swift_mailer
            from_email: error@raac.tobeonthe.net
            to_email: mhauptma73@gmail.com
            subject: Error on raac.tobeonthe.net
            level: debug
