management:
    resource: "@ManagementBundle/Controller/"
    type:     annotation
    prefix:   /

cart:
    resource: "@CartBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
member:
    resource: "@MemberBundle/Controller/"
    type:     annotation
    prefix:   /

producer:
    resource: "@ProducerBundle/Controller/"
    type:     annotation
    prefix:   /

consumer:
    resource: "@ConsumerBundle/Controller/"
    type:     annotation
    prefix:   /

product:
    resource: "@ProductBundle/Controller/"
    type:     annotation
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"