<?php

namespace NewsBundle\Repository;

/**
 * NewsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNewest()
    {
        return $this
            ->createQueryBuilder('n')
            ->setMaxResults(3)
            ->getQuery()
            ->getResult()
        ;
    }
}
