services:
  media.namer:
    class: MediaBundle\Naming\MediaNamer
  media.directory_namer:
    class: MediaBundle\Naming\MediaDirectoryNamer
    arguments: ["@doctrine.orm.entity_manager"]
  media.events.upload:
        class: MediaBundle\Event\UploadEventSubscriber
        calls:
            - ["setEntityManager", ["@doctrine.orm.entity_manager"]]
        tags:
            - {name:"kernel.event_listener", event:"vich_uploader.post_upload", method:"onPostUpload"}
  media.form.type.directory:
        class: MediaBundle\Form\DirectoryType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
  media.form.type.media:
        class: MediaBundle\Form\MediaType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
  media.form.type.file:
        class: MediaBundle\Form\Type\FileType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
