services:
    admin.category:
        class: UserBundle\Admin\UserAdmin
        arguments: [~, UserBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User, group: users }
    users.manager.user:
        class: UserBundle\Manager\UserManager
        arguments: ["@doctrine.orm.entity_manager","@security.token_storage"]
        calls:
            - [setRequest, ["@request_stack"]]
            - [setTwig, ["@twig"]]
            - [setTranslator, ["@translator"]]
            - [setMailer, ["@mailer"]]
    user.events.consumer:
        class: UserBundle\Event\ConsumerEventSubscriber
        calls:
            - ["setEntityManager", ["@doctrine.orm.entity_manager"]]
            - ["setMailer", ["@mailer"]]
            - [setTwig, ["@twig"]]
            - [setTranslator, ["@translator"]]
        tags:
            - {name:"kernel.event_listener", event:"user.events.consumerCreated", method:"onConsumerCreated"}
    user.events.visit:
        class: UserBundle\Event\VisitEventSubscriber
        calls:
            - ["setEntityManager", ["@doctrine.orm.entity_manager"]]
            - ["setMailer", ["@mailer"]]
            - [setTwig, ["@twig"]]
            - [setTranslator, ["@translator"]]
        tags:
            - {name:"kernel.event_listener", event:"producer.events.visitPersisted", method:"onVisitSaved"}
            - {name:"kernel.event_listener", event:"producer.events.visitCompleted", method:"onVisitCompleted"}
    user.manager.login:
        class: UserBundle\Manager\LoginManager
        arguments:
            - "@security.token_storage"
            - "@security.user_checker"
            - "@security.authentication.session_strategy"
            - "@request_stack"
            - null
    user.db_user_provider:
        class: UserBundle\Security\User\DbUserProvider
        arguments:
            - "@doctrine.orm.entity_manager"