parameters:
    twitter_typeahead.typeahead_type.class: AppBundle\Form\Type\TypeaheadType
    twitter_typeahead.twig_extension.class: AppBundle\Twig\Extension\TypeaheadTwigExtension

services:
    # provide twig functions
    twitter_typeahead.twig_extension:
        class: "%twitter_typeahead.twig_extension.class%"
        tags: [{ name: twig.extension }]
        
    # main typeahead autocomplete form field
    twitter_typeahead.typeahead_type:
        class: "%twitter_typeahead.typeahead_type.class%"
        arguments: ["@service_container", "@doctrine.orm.entity_manager", "@router"]
        tags:
            - {name: form.type, alias: entity_typeahead }
    app.form.type.image:
        class: AppBundle\Form\Type\ImageType
        tags:
            - { name: form.type }
    app.image_type_extension:
        class: AppBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }
    app.help_type_extension:
        class: AppBundle\Form\Extension\HelpTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
    hidden_entity.type:
        class: AppBundle\Form\Type\HiddenEntityType
        arguments: ["@doctrine"]
        tags:
            - { name: form.type, alias: hidden_entity }
    app.download_type_extension:
        class: AppBundle\Form\Extension\DownloadTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }
    app.manager.log:
        class: AppBundle\Manager\LogManager
        arguments: ["@doctrine.orm.entity_manager","@security.token_storage"]