services:
  member.admin.member:
        class: MemberBundle\Admin\MemberAdmin
        arguments: [~, MemberBundle\Entity\Member, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: members, label: Member }