services:
#    producer.example:
#        class: ProducerBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    producer.admin.stock:
        class: ProducerBundle\Admin\StockAdmin
        arguments: [~, ProducerBundle\Entity\Stock, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: products, label: Stock }

    producer.admin.member:
        class: ProducerBundle\Admin\MemberAdmin
        arguments: [~, ProducerBundle\Entity\Member, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: members, label: Producers }

    producer.admin.property:
        class: ProducerBundle\Admin\PropertyAdmin
        arguments: [~, ProducerBundle\Entity\Property, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: members, label: Properties }
