services:
    producer.admin.stock:
        class: ProducerBundle\Admin\StockAdmin
        arguments: [~, ProducerBundle\Entity\Stock, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: products, label: Stock }

    producer.admin.member:
        class: ProducerBundle\Admin\MemberAdmin
        arguments: [~, ProducerBundle\Entity\Member, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: members, label: Producers }

    producer.admin.property:
        class: ProducerBundle\Admin\PropertyAdmin
        arguments: [~, ProducerBundle\Entity\Property, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: members, label: Properties }

    app.form.registration:
        class: ProducerBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    producer.events.visit:
        class: ProducerBundle\Event\VisitEventSubscriber
        calls:
            - ["setEntityManager", ["@doctrine.orm.entity_manager"]]
        tags:
            - {name:"kernel.event_listener", event:"producer.events.visitPersisted", method:"onVisitSaved"}