services:
    producer.admin.stock:
        class: ProducerBundle\Admin\StockAdmin
        arguments: [~, ProducerBundle\Entity\Stock, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: products, label: Stock }

    producer.admin.member:
        class: ProducerBundle\Admin\MemberAdmin
        arguments: [~, ProducerBundle\Entity\Member, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: members, label: Producers }

    producer.admin.property:
        class: ProducerBundle\Admin\PropertyAdmin
        arguments: [~, ProducerBundle\Entity\Property, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: members, label: Properties }

    app.form.registration:
        class: ProducerBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    producer.events.visit:
        class: ProducerBundle\Event\VisitEventSubscriber
        calls:
            - ["setEntityManager", ["@doctrine.orm.entity_manager"]]
            - ["setProducerManager", ["@producer.manager.producer"]]
        tags:
            - {name:"kernel.event_listener", event:"producer.events.visitPersisted", method:"onVisitSaved"}
    producer.events.producer:
        class: ProducerBundle\Event\ProducerEventSubscriber
        calls:
            - ["setEntityManager", ["@doctrine.orm.entity_manager"]]
            - ["setMailer", ["@mailer"]]
            - [setTwig, ["@twig"]]
            - [setTranslator, ["@translator"]]
            - [setLogManager, ["@app.manager.log"]]
        tags:
            - {name:"kernel.event_listener", event:"producer.events.producerCreated", method:"onProducerCreated"}

    producer.events.property:
        class: ProducerBundle\Event\PropertyEventSubscriber
        calls:
            - ["setEntityManager", ["@doctrine.orm.entity_manager"]]
            - ["setMailer", ["@mailer"]]
            - [setTwig, ["@twig"]]
            - [setTranslator, ["@translator"]]
            - [setLogManager, ["@app.manager.log"]]
        tags:
            - {name:"kernel.event_listener", event:"producer.events.propertyCreated", method:"onPropertyCreatedByConsumer"}

    producer.manager.producer:
        class: ProducerBundle\Manager\ProducerManager
        arguments: ["@doctrine.orm.entity_manager","@security.token_storage","@event_dispatcher","@mailer","@twig","@translator","@request_stack"]