<?php

namespace ProducerBundle\Repository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends \MemberBundle\Repository\MemberRepository
{
	public function getUser(\FOS\UserBundle\Model\UserInterface $user)
	{
		$em = $this->getEntityManager();

		$q = $em->createQuery(
			'SELECT
				m,
				pm,
				u
			FROM
				ProducerBundle:Member pm
			LEFT JOIN
				pm.Member m
			LEFT JOIN
				m.User u
			WHERE
				m.User = :user'
		);
		$q->setParameter('user', $user);

		return $q->getOneOrNullResult();
	}
}
