<?php

namespace ProducerBundle\Repository;

/**
 * MemberRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUser(\FOS\UserBundle\Model\UserInterface $user)
    {
        $em = $this->getEntityManager();

        $q = $em->createQuery(
            'SELECT
				u,
				p
			FROM
				ProducerBundle:Member p
			LEFT JOIN
				p.User u
			WHERE
				u.id = :user_id'
        );
        $q->setParameter('user_id', $user->getId());

        return $q->getOneOrNullResult();
    }
}
