<?php

namespace ProducerBundle\Repository;

use NodeBundle\Entity\Node;

/**
 * PropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyRepository extends \Doctrine\ORM\EntityRepository
{
	public function findbyUser(\FOS\UserBundle\Model\UserInterface $user)
	{
		$em = $this->getEntityManager();

		$q = $em->createQuery(
			'SELECT
				p
			FROM
				ProducerBundle:Property p
			LEFT JOIN
				p.Member pm
			WHERE
				pm.User = :user'
		);
		$q->setParameter('user', $user);

		return $q->getResult();
	}

	public function getByNode(Node $node)
	{
		return $this
            ->createQueryBuilder('p')
            ->select('p')
            ->leftJoin('p.Member', 'm')
            ->leftJoin('m.User', 'u')
            ->andWhere('u.Node = :node')
            ->setParameter('node', $node)
            ->getQuery()
            ->getResult();
	}

	public function getLatestByNode($maxResults = 10, Node $node = null)
    {
        return $this
            ->createQueryBuilder('p')
            ->select('p')
            ->leftJoin('p.Member', 'm')
            ->leftJoin('m.User', 'u')
            ->andWhere('u.Node = :node')
            ->orderBy('p.created', 'DESC')
            ->setParameter('node', $node)
            ->setMaxResults($maxResults)
            ->getQuery()
            ->getResult()
        ;
    }

    public function getPropertiesWithLocation()
    {
        return $this
            ->createQueryBuilder('p')
            ->select('p')
            ->leftJoin('p.Member', 'm')
            ->leftJoin('m.User', 'u')
            ->andWhere('p.Location IS NOT NULL')
            ->getQuery()
            ->getResult();
    }
}
