<?php

namespace ProducerBundle\Repository;

/**
 * VisitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitRepository extends \Doctrine\ORM\EntityRepository
{
	public function getVisitsForParticipant($participant)
	{
		return $this
            ->createQueryBuilder('v')
            ->leftJoin('v.Participants', 'p')
            ->where('p = :user')
            ->setParameter('user', $participant)
            ->getQuery()
            ->getResult();
	}

      public function getUpcoming()
      {
            return $this
            ->createQueryBuilder('v')
            ->where('v.visitDate IS NULL OR v.visitDate > :today')
            ->orderBy('v.visitDate', 'ASC')
            ->setParameter('today', new \DateTime())
            ->setMaxResults(10)
            ->getQuery()
            ->getResult()
        ;
      }
}
