<?php

namespace ProducerBundle\Repository;

/**
 * VisitProductionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitProductionRepository extends \Doctrine\ORM\EntityRepository
{
}
